// ==================================================
// BabyBasen — articles.js
// De lange artikler under Viden, på begge sprog.
// Alt her kan redigeres i admin under fanen Artikler.
// ==================================================

const DEFAULT_ARTICLES = {

    sleepTitle: { da: "Viden om søvn", en: "About baby sleep" },
    sleepSub:   { da: "Sådan sover børn fra fødslen til 3-års alderen.", en: "How children sleep from birth to age three." },

    sleepCards: [
        {
            title: { da: "0-3 måneder: Den fjerde trimester", en: "0-3 months: the fourth trimester" },
            body: {
                da: "<p>Nyfødte sover typisk 14-17 timer i døgnet, men i små bidder på 2-4 timer – uden forskel på nat og dag. Døgnrytmen er slet ikke udviklet endnu, og kroppen producerer først sit eget søvnhormon (melatonin) omkring 2-3 måneders alderen.</p><p>Søvncyklussen er kun ca. 40-50 minutter, og halvdelen af søvnen er \"aktiv\" REM-søvn, hvor baby grynter, smiler, spjætter og laver lyde. Det er helt normalt – lad være med at tage baby op ved den mindste lyd, for ofte sover barnet stadig.</p><p><strong>Brug lyden:</strong> I livmoderen var der konstant larm fra puls, blodgennemstrømning og mave. Total stilhed er faktisk utrygt for en nyfødt. Konstante, monotone lyde genskaber livmoderens lydtapet og aktiverer beroligelsesrefleksen.</p>",
                en: "<p>Newborns sleep 14-17 hours a day, but in short stretches of 2-4 hours — with no sense of night and day. The body clock isn't developed yet, and the body only starts producing its own sleep hormone (melatonin) at around 2-3 months.</p><p>The sleep cycle is only about 40-50 minutes, and half of it is \"active\" REM sleep, where your baby grunts, smiles, twitches and makes noises. That's completely normal — don't pick them up at the slightest sound, because they're often still asleep.</p><p><strong>How the sound helps:</strong> The womb was constantly noisy with pulse, blood flow and digestion. Total silence is actually unsettling for a newborn. Steady, monotonous sound recreates that backdrop and triggers the calming reflex.</p>"
            }
        },
        {
            title: { da: "3-6 måneder: Søvnen bliver \"voksen\"", en: "3-6 months: sleep grows up" },
            body: {
                da: "<p>Omkring 4 måneder sker en stor og permanent ændring: {navn}s søvn omorganiseres til voksne søvnstadier med lette og dybe faser. Det er den berømte <strong>4-måneders søvnregression</strong> – barnet vågner nu kortvarigt op mellem hver søvncyklus, og hvis omstændighederne har ændret sig (lyden er væk, sutten er faldet ud), vågner det helt.</p><p>Samlet søvn: 12-16 timer i døgnet, typisk fordelt på 3-4 lure om dagen. Nattesøvnen begynder langsomt at samle sig i længere stræk.</p><p><strong>Brug lyden:</strong> En konstant lyd fungerer som en bro mellem søvncyklusserne. Når barnet vågner let op og hører præcis det samme som ved indsovning, glider det videre i søvnen uden at vågne helt.</p>",
                en: "<p>At around four months a big and permanent change happens: {navn}'s sleep reorganises into adult sleep stages with light and deep phases. This is the famous <strong>four-month sleep regression</strong> — your baby now briefly surfaces between every sleep cycle, and if things have changed (the sound is gone, the dummy fell out), they wake fully.</p><p>Total sleep: 12-16 hours a day, usually across 3-4 naps. Night sleep slowly starts to consolidate.</p><p><strong>How the sound helps:</strong> A constant sound acts as a bridge between sleep cycles. When your baby surfaces and hears exactly what they heard falling asleep, they slide back under without waking properly.</p>"
            }
        },
        {
            title: { da: "6-12 måneder: Rytme og separationsangst", en: "6-12 months: rhythm and separation anxiety" },
            body: {
                da: "<p>Søvnen bliver mere forudsigelig, og de fleste går fra 3 til 2 lure. Samlet søvnbehov: 12-15 timer i døgnet. Mange kan nu sove længere stræk om natten, men opvågninger er stadig normale.</p><p>To ting kan drille: <strong>Motorisk udvikling</strong> (kravle, rejse sig, stå) betyder, at hjernen \"øver\" om natten, og barnet kan vågne stående i tremmesengen. Og omkring 8-10 måneder rammer <strong>separationsangsten</strong> – barnet forstår nu, at mor og far findes, selv når de er væk.</p><p><strong>Brug lyden:</strong> Lyden er nu blevet et betinget søvnsignal: Når barnet hører den, ved hjernen, at nu er det sovetid. Den maskerer også lyde fra resten af hjemmet.</p>",
                en: "<p>Sleep becomes more predictable, and most babies go from three naps to two. Total need: 12-15 hours a day. Many can now sleep longer stretches at night, though waking is still normal.</p><p>Two things can get in the way. <strong>Motor development</strong> (crawling, pulling up, standing) means the brain \"practises\" at night, and your baby may wake up standing in the cot. And at around 8-10 months <strong>separation anxiety</strong> arrives — your baby now understands that you exist even when you're out of sight.</p><p><strong>How the sound helps:</strong> The sound has become a conditioned sleep cue: when your baby hears it, the brain knows it's time to sleep. It also masks noise from the rest of the house.</p>"
            }
        },
        {
            title: { da: "1-2 år: Fra to lure til én", en: "1-2 years: from two naps to one" },
            body: {
                da: "<p>Søvnbehov: 11-14 timer i døgnet. Et sted mellem 12 og 18 måneder dropper de fleste formiddagsluren og går til én lang middagslur på 1,5-3 timer. Overgangen kan give nogle rodede uger med et overtræt barn sidst på dagen – ryk puttetiden tidligere i den periode.</p><p>Nye udfordringer: Sprogeksplosionen og viljen! Barnet kan nu protestere aktivt mod at skulle sove, og omkring 18 måneder kommer ofte en ny søvnregression drevet af selvstændighedstrang og tandfrembrud.</p><p><strong>Brug lyden:</strong> En fast lyd som en del af putteritualet giver forudsigelighed og tryghed – to ting, som et 1-2-årigt barn har brug for.</p>",
                en: "<p>Sleep need: 11-14 hours a day. Somewhere between 12 and 18 months most children drop the morning nap and move to one long midday nap of 1.5-3 hours. The transition can bring a few messy weeks with an overtired child by late afternoon — move bedtime earlier during that period.</p><p>New challenges: the language explosion, and the will! Your child can now actively protest about sleeping, and around 18 months another regression often arrives, driven by a push for independence and teething.</p><p><strong>How the sound helps:</strong> A fixed sound as part of the bedtime routine gives predictability and security — two things a one-to-two-year-old needs.</p>"
            }
        },
        {
            title: { da: "2-3 år: Drømme, mørkeræd og den store seng", en: "2-3 years: dreams, dark and the big bed" },
            body: {
                da: "<p>Søvnbehov: 10-13 timer i døgnet. Middagsluren skrumper – nogle dropper den helt omkring 3-års alderen, andre holder fast til 4-5 år. Barnet kan nu udskyde og forhandle (\"én historie til!\"), og faste, kærlige rammer omkring sengetid bliver vigtigere end nogensinde.</p><p>Fantasien eksploderer, og med den kommer <strong>mareridt</strong> (barnet vågner bange og kan trøstes) og hos nogle <strong>natterædsler</strong> (barnet skriger og virker vågent, men sover faktisk). Mørkeræd er også almindeligt nu – en svag natlampe med varmt lys er fint.</p><p><strong>Brug lyden:</strong> Rolige, ensartede lyde hjælper det tankemylder, som et 2-3-årigt hoved er fuldt af, med at falde til ro.</p>",
                en: "<p>Sleep need: 10-13 hours a day. The midday nap shrinks — some drop it around age three, others keep it until four or five. Your child can now delay and negotiate (\"one more story!\"), and firm, loving boundaries around bedtime matter more than ever.</p><p>Imagination explodes, and with it come <strong>nightmares</strong> (your child wakes frightened and can be comforted) and for some <strong>night terrors</strong> (your child screams and seems awake but is actually asleep). Fear of the dark is common now too; a dim, warm night light is fine.</p><p><strong>How the sound helps:</strong> Calm, even sound helps settle the racing thoughts a two-to-three-year-old head is full of.</p>"
            }
        },
        {
            title: { da: "⏱️ Vågetider: Hvor længe kan barnet være vågen?", en: "⏱️ Wake windows: how long can they stay awake?" },
            body: {
                da: "<p>Et af de bedste værktøjer mod putte-kampe er at ramme \"søvnvinduet\" – putte barnet, inden det bliver overtræt. Vejledende vågetid mellem lure:</p><table class=\"wake-table\"><tr><th>Alder</th><th>Vågetid</th><th>Antal lure</th></tr><tr><td>0-3 mdr.</td><td>45-90 min.</td><td>4-6</td></tr><tr><td>3-6 mdr.</td><td>1,5-2,5 timer</td><td>3-4</td></tr><tr><td>6-9 mdr.</td><td>2-3 timer</td><td>2-3</td></tr><tr><td>9-12 mdr.</td><td>2,5-3,5 timer</td><td>2</td></tr><tr><td>12-18 mdr.</td><td>3-5 timer</td><td>1-2</td></tr><tr><td>18 mdr.-3 år</td><td>5-6 timer</td><td>0-1</td></tr></table><p style=\"margin-top:10px;\">Tegn på træthed: gnider øjne, kigger væk, gaber, bliver \"fjern\". Tegn på overtræthed: hektisk, pylret, buer ryggen.</p>",
                en: "<p>One of the best tools against bedtime battles is hitting the \"sleep window\" — settling your child before they become overtired. Guideline wake times between naps:</p><table class=\"wake-table\"><tr><th>Age</th><th>Wake window</th><th>Naps</th></tr><tr><td>0-3 mo</td><td>45-90 min</td><td>4-6</td></tr><tr><td>3-6 mo</td><td>1.5-2.5 hours</td><td>3-4</td></tr><tr><td>6-9 mo</td><td>2-3 hours</td><td>2-3</td></tr><tr><td>9-12 mo</td><td>2.5-3.5 hours</td><td>2</td></tr><tr><td>12-18 mo</td><td>3-5 hours</td><td>1-2</td></tr><tr><td>18 mo-3 yr</td><td>5-6 hours</td><td>0-1</td></tr></table><p style=\"margin-top:10px;\">Signs of tiredness: rubbing eyes, looking away, yawning, going glassy-eyed. Signs of being overtired: hectic, fretful, arching the back.</p>"
            }
        },
        {
            title: { da: "🌙 Den gode putterutine", en: "🌙 A good bedtime routine" },
            body: {
                da: "<p>Børn elsker forudsigelighed. En kort, fast rutine på 15-30 minutter i samme rækkefølge hver aften fortæller kroppen, at søvnen er på vej:</p><ul class=\"leap-list\"><li>Dæmp lys og tempo i hjemmet den sidste time.</li><li>Bad eller vask → ren ble → nattøj.</li><li>Mad/amning (gerne før barnet er helt væk).</li><li>Historie, sang eller stille pusletid.</li><li>Tænd den samme lyd – {navn}s eget søvnsignal.</li><li>Læg barnet døsigt, men vågent, i sengen.</li></ul>",
                en: "<p>Children love predictability. A short, fixed routine of 15-30 minutes in the same order every evening tells the body that sleep is coming:</p><ul class=\"leap-list\"><li>Dim the lights and slow the pace for the last hour.</li><li>Bath or wash → clean nappy → sleepwear.</li><li>Feed (ideally before they're fully gone).</li><li>A story, a song, or quiet time.</li><li>Start the same sound — {navn}'s own sleep cue.</li><li>Put your child down drowsy but awake.</li></ul>"
            }
        },
        {
            title: { da: "🛡️ Tryg søvn – de vigtigste råd", en: "🛡️ Safe sleep — the essentials" },
            body: {
                da: "<ul class=\"leap-list\"><li>Læg altid baby til at sove på ryggen det første år.</li><li>Fast madras, ingen løse dyner, puder eller bamser i sengen de første måneder – brug evt. sovepose.</li><li>Sov i samme rum som barnet de første 6 måneder (egen seng).</li><li>Hold soveværelset køligt (ca. 18-20 °C) og røgfrit.</li><li>Lydstyrke: Placér højttaleren mindst 1-2 meter fra barnet og hold lyden dæmpet.</li></ul><p style=\"margin-top:10px; font-size:0.85rem; color:var(--text-light);\">BabyBasen er en hjælp til hverdagen – ikke sundhedsfaglig rådgivning. Er du bekymret, så tal med sundhedsplejersken eller lægen.</p>",
                en: "<ul class=\"leap-list\"><li>Always place your baby on their back to sleep for the first year.</li><li>Firm mattress, no loose duvets, pillows or soft toys in the first months — use a sleeping bag instead.</li><li>Sleep in the same room as your baby (in their own bed) for the first six months.</li><li>Keep the room cool (about 18-20 °C) and smoke-free.</li><li>Volume: place the speaker at least 1-2 metres from your baby and keep it soft.</li></ul><p style=\"margin-top:10px; font-size:0.85rem; color:var(--text-light);\">BabyBase is an everyday helper, not medical advice. If you're worried, talk to your health visitor or doctor.</p>"
            }
        }
    ],

    leapTitle: { da: "Tigerspring", en: "Leaps" },
    leapSub: { da: "De 10 mentale udviklingsspring i barnets første 20 måneder.", en: "The 10 mental developmental leaps of the first 20 months." },
    leapStatusTitle: { da: "Hvor er {navn} lige nu?", en: "Where is {navn} right now?" },
    leapIntroTitle: { da: "Hvad er et tigerspring?", en: "What is a leap?" },
    leapIntroBody: {
        da: "<p>Udover at vokse fysisk gennemgår alle babyer 10 store <strong>mentale</strong> udviklingsspring i løbet af de første ca. 20 måneder. Ved hvert spring modnes hjernen pludseligt, og barnet kan opfatte verden på en helt ny måde. Det er fantastisk – men også skræmmende, for alt det velkendte føles pludselig anderledes.</p><p>Springene kommer på overraskende faste tidspunkter og regnes altid fra <strong>terminsdatoen</strong> – ikke fødselsdagen.</p><h4 style=\"margin-top: 15px;\">De typiske tegn:</h4><ul class=\"leap-list\"><li><strong>Grædende</strong> – mere pylret og let til tårer end normalt.</li><li><strong>Klæbende</strong> – vil bæres og være tæt på mor eller far hele tiden.</li><li><strong>Gnaven</strong> – urolig søvn, dårlig appetit, humørsvingninger.</li></ul><p style=\"margin-top: 15px;\"><strong>Sådan hjælper lyden:</strong> Under et spring bombarderes hjernen med nye indtryk. Monotone, brummende lyde skærmer for indtrykkene og giver hjernen en tiltrængt pause.</p>",
        en: "<p>As well as growing physically, all babies go through 10 major <strong>mental</strong> developmental leaps during roughly the first 20 months. At each leap the brain matures suddenly, and your baby can perceive the world in a completely new way. It's wonderful — but also frightening, because everything familiar suddenly feels different.</p><p>The leaps arrive at surprisingly fixed times, and they are always counted from the <strong>due date</strong>, not the birthday.</p><h4 style=\"margin-top: 15px;\">The three classic signs:</h4><ul class=\"leap-list\"><li><strong>Crying</strong> — more fretful and quicker to tears than usual.</li><li><strong>Clinging</strong> — wants to be held and close to you all the time.</li><li><strong>Cranky</strong> — restless sleep, poor appetite, mood swings.</li></ul><p style=\"margin-top: 15px;\"><strong>How the sound helps:</strong> During a leap the brain is bombarded with new input. Monotonous, humming sound screens out the impressions and gives the brain a much-needed break.</p>"
    },

    leapCards: [
        { nr: 1, from: 4, to: 5, title: { da: "Sanseindtryk", en: "Sensations" },
          body: { da: "<p>Alle sanser skærpes på én gang. Verden bliver skarpere, lysere og mere larmende – indefra mærker baby nu også sin egen fordøjelse tydeligere.</p><p><strong>Bagefter kan baby:</strong> Kigge længere og mere fokuseret, reagere tydeligere på lyde og berøring – og give jer det allerførste rigtige smil.</p>",
                  en: "<p>All the senses sharpen at once. The world becomes brighter, sharper and louder — and from the inside, your baby now feels their own digestion more clearly.</p><p><strong>Afterwards your baby can:</strong> Look longer and more intently, respond more clearly to sound and touch — and give you that first real smile.</p>" } },
        { nr: 2, from: 7, to: 9, title: { da: "Mønstre", en: "Patterns" },
          body: { da: "<p>Baby begynder at opdage simple mønstre – både i det, den ser (striber, kontraster, egne hænder!), og i det, den mærker.</p><p><strong>Bagefter kan baby:</strong> Holde hovedet mere stabilt, lave små kontrollerede bevægelser, pludre og studere ting længe.</p>",
                  en: "<p>Your baby starts noticing simple patterns — both in what they see (stripes, contrasts, their own hands!) and in what they feel.</p><p><strong>Afterwards your baby can:</strong> Hold their head more steadily, make small controlled movements, coo and study things for a long time.</p>" } },
        { nr: 3, from: 11, to: 12, title: { da: "Glidende overgange", en: "Smooth transitions" },
          body: { da: "<p>Nu opfattes bløde, glidende forandringer: en stemme der går op og ned, en bevægelse der glider hen over rummet. Babys egne bevægelser bliver også mere flydende.</p><p><strong>Bagefter kan baby:</strong> Følge ting med øjnene i én glidende bevægelse, hvine og \"synge\" med tonefald, og gribe mere målrettet.</p>",
                  en: "<p>Your baby now perceives smooth, gradual change: a voice rising and falling, a movement gliding across the room. Their own movements also become more fluid.</p><p><strong>Afterwards your baby can:</strong> Follow objects with their eyes in one smooth movement, squeal and \"sing\" with intonation, and reach more purposefully.</p>" } },
        { nr: 4, from: 14, to: 19, title: { da: "Begivenheder", en: "Events" },
          body: { da: "<p>Det længste og ofte hårdeste spring – og det falder typisk sammen med 4-måneders søvnregressionen. Baby forstår nu korte \"begivenheder\": at én ting fører til den næste.</p><p><strong>Bagefter kan baby:</strong> Gribe, vende og undersøge ting bevidst, putte alt i munden, reagere på sit eget navn og måske trille rundt.</p>",
                  en: "<p>The longest and often hardest leap — and it typically coincides with the four-month sleep regression. Your baby now grasps short \"events\": that one thing leads to the next.</p><p><strong>Afterwards your baby can:</strong> Grasp, turn and examine things deliberately, put everything in their mouth, respond to their own name and perhaps roll over.</p>" } },
        { nr: 5, from: 22, to: 26, title: { da: "Sammenhænge", en: "Relationships" },
          body: { da: "<p>Baby forstår nu afstande – og dermed den skræmmende opdagelse, at mor og far kan bevæge sig VÆK. Det er startskuddet til separationsangsten.</p><p><strong>Bagefter kan baby:</strong> Sidde mere selv, flytte ting fra hånd til hånd, kigge efter tabte ting og protestere højlydt, når du forlader rummet.</p>",
                  en: "<p>Your baby now understands distance — and with it the alarming discovery that you can move AWAY. That's the start of separation anxiety.</p><p><strong>Afterwards your baby can:</strong> Sit more independently, move objects hand to hand, look for dropped things and protest loudly when you leave the room.</p>" } },
        { nr: 6, from: 33, to: 37, title: { da: "Kategorier", en: "Categories" },
          body: { da: "<p>Verden bliver sorteret! Baby opdager, at ting kan grupperes: en hund er en hund, uanset om den er stor, lille, på billede eller i virkeligheden.</p><p><strong>Bagefter kan baby:</strong> Genkende kategorier (dyr, mad, mennesker), vise tydelige præferencer og forstå enkelte ord.</p>",
                  en: "<p>The world gets sorted! Your baby discovers that things can be grouped: a dog is a dog, whether big, small, in a picture or in real life.</p><p><strong>Afterwards your baby can:</strong> Recognise categories (animals, food, people), show clear preferences and understand individual words.</p>" } },
        { nr: 7, from: 41, to: 46, title: { da: "Rækkefølger", en: "Sequences" },
          body: { da: "<p>Baby forstår nu, at ting skal gøres i en bestemt rækkefølge for at lykkes: Først klodsen op, SÅ slippe den i spanden.</p><p><strong>Bagefter kan baby:</strong> Stable, putte ting i og ud af beholdere, pege på ting den vil have, sige de første rigtige ord og måske tage de første skridt.</p>",
                  en: "<p>Your baby now understands that things must happen in a particular order to work: first pick up the block, THEN drop it in the bucket.</p><p><strong>Afterwards your baby can:</strong> Stack, put things in and out of containers, point at what they want, say their first real words and perhaps take their first steps.</p>" } },
        { nr: 8, from: 50, to: 55, title: { da: "Programmer", en: "Programmes" },
          body: { da: "<p>Efter rækkefølger kommer \"programmer\": fleksible planer med et mål. Barnet forstår nu hele forløb som \"at spise frokost\" – og VIL selv!</p><p><strong>Bagefter kan barnet:</strong> Efterligne hverdagsopgaver, hjælpe med påklædning og lege begyndende \"som om\"-lege.</p>",
                  en: "<p>After sequences come \"programmes\": flexible plans with a goal. Your child now understands whole routines like \"having lunch\" — and wants to do it themselves!</p><p><strong>Afterwards your child can:</strong> Imitate everyday tasks, help with getting dressed and start simple pretend play.</p>" } },
        { nr: 9, from: 59, to: 64, title: { da: "Principper", en: "Principles" },
          body: { da: "<p>Barnet begynder at tænke over sin egen tænkning: at planlægge, forhandle og – ja – teste grænser med fuldt overlæg. Trodsalderens spæde start!</p><p><strong>Bagefter kan barnet:</strong> Planlægge små \"projekter\", lave sjov med jer, efterligne strategisk og vise begyndende forståelse for \"mit\" og \"dit\".</p>",
                  en: "<p>Your child begins to think about their own thinking: planning, negotiating and — yes — testing boundaries quite deliberately. The first hints of the terrible twos.</p><p><strong>Afterwards your child can:</strong> Plan small \"projects\", joke with you, imitate strategically and show early understanding of \"mine\" and \"yours\".</p>" } },
        { nr: 10, from: 70, to: 76, title: { da: "Systemer", en: "Systems" },
          body: { da: "<p>Det sidste store spring (ca. 17 måneder). Barnet forstår nu \"systemer\": familien er ét system, naboens familie et andet. Samvittigheden vågner.</p><p><strong>Bagefter kan barnet:</strong> Vise omsorg, genkende sig selv i spejlet, lege mere avancerede fantasilege og sætte ord sammen til små sætninger.</p>",
                  en: "<p>The last big leap (around 17 months). Your child now understands \"systems\": the family is one system, the neighbours' family another. Conscience awakens.</p><p><strong>Afterwards your child can:</strong> Show care, recognise themselves in the mirror, engage in richer pretend play and put words together into short sentences.</p>" } }
    ],

    leapOutroTitle: { da: "Godt at huske", en: "Worth remembering" },
    leapOutroBody: {
        da: "<ul class=\"leap-list\"><li>Springperioderne varer typisk 1-6 uger – de tidlige er korte, de sene længere.</li><li>Uro og dårlig søvn i et spring er et sundhedstegn: hjernen arbejder på højtryk.</li><li>Efter hvert spring kommer en solskinsperiode, hvor barnet pludselig kan nye ting.</li><li>Alle datoer er vejledende – dit barn er ikke \"bagud\", fordi et spring kommer en uge senere.</li></ul>",
        en: "<ul class=\"leap-list\"><li>Leap periods usually last 1-6 weeks — the early ones are short, the later ones longer.</li><li>Restlessness and poor sleep during a leap is a good sign: the brain is working overtime.</li><li>After every leap comes a sunny period where your child can suddenly do new things.</li><li>All the dates are guidelines — your child isn't \"behind\" because a leap arrives a week later.</li></ul>"
    }
};
